apiVersion: v1
kind: Service
metadata:
  name: oscon-rating-web
  labels:
    name: oscon-rating-web
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: oscon-rating-web
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oscon-rating-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: oscon-rating-web
  template:
    metadata:
      labels:
        app: oscon-rating-web
    spec:
      imagePullSecrets:
        - name: acr-secret
      containers:
      - name: oscon-rating-web
        image: "{{.Values.image}}:{{.Values.imageTag}}"
        env:
        - name: SITE_API
          value: "{{.Values.apiSites}}"
        - name: SUBJECT_API
          value: "{{.Values.apiSubjects}}"
        - name: RATING_API
          value: "{{.Values.apiRatings}}"
        resources:
          requests:
            cpu: "100m"
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
